icecream <- read.csv("C:/Users/Jeevan/Desktop/Christ University/Statistics/icecream.csv")
View(icecream)
str(icecream)
icecream$Solid <- as.factor(icecream$Solid)
icecream$Judges <- as.factor(icecream$Judges)
str(icecream)
boxplot(Score~Solid, data = icecream, xlab = "solid", ylab = "score", col = c("#00AFBB", "#E7B800"))
boxplot(Score~Judges, data = icecream, xlab = "judges", ylab = "score", col = c("#00AFBB", "#E7B800"))
model<-aov(Score~Judges+Solid, data = icecream)
summary(model)
library(lsmeans)
lm1<-lm(Score~Judges+Solid, data=icecream)
lsm1<-lsmeans(lm1,"Solid")
lsm1
pairs(lsm1)
library(multcompView) 
CLD(lsm1,Letters = "abcde")
lsm2<-lsmeans(lm1,"Judges")
lsm2
pairs(lsm2)
