interaction<-read.table(file = "clipboard",header = TRUE)
View(interaction)
str(interaction)
boxplot(yld~var, data = interaction, xlab = "Variety", ylab = "Yield", col = c("#00AFBB", "#E7B800")) 
boxplot(yld~fer, data = interaction, xlab = "Fertilizer", ylab = "Yield", col = c("#00AFBB", "#E7B800"))
boxplot(yld~interaction, data = interaction, xlab = "Fertilizer*variety", ylab = "Yield",col = c("#00AFBB", "#E7B800"))
model<-aov(yld~fer+var+fer*var, data = interaction)
summary(model)
library(lsmeans)
lm1<-lm(yld~fer+var+fer*var, data=interaction) 
lsm1<-lsmeans(lm1,"var") 
pairs(lsm1)
lsm2<-lsmeans(lm1,~fer:var)
lsm2
pairs(lsm2)
library(multcompView)
CLD(lsm1,Letters = "abcde")
CLD(lsm2,Letters = "abcdefgh")