library(readxl)
Lab8_data <- read_excel("C:/Users/Jeevan/Desktop/Christ University/Statistics/DOE/Lab8_data.xlsx")
View(Lab8_data)
attach(Lab8_data)
boxplot(yield~fac1,data = Lab8_data,xlab = "Nitrogen",ylab = "Yield",col = c("#00AFBB","#E7B800"))
boxplot(yield~fac2,data = Lab8_data,xlab = "Phosphate",ylab = "Yield",col = c("#00AFBB","#E7B800"))
boxplot(yield~interaction,data = Lab8_data,xlab = "NP",ylab = "Yield",col = c("#00AFBB","#E7B800"))
model <- aov(yield~fac1+fac2+fac1*fac2,data = Lab8_data)
summary(model)