library(readxl)
Lab8_data <- read_excel("C:/Users/Jeevan/Desktop/Christ University/Statistics/DOE/Lab8_data.xlsx")
View(Lab8_data)
attach(Lab8_data)
boxplot(yield~fac1,data = Lab8_data,xlab = "Nitrogen",ylab = "Yield",col = c("#00AFBB","#E7B800"))
boxplot(yield~fac2,data = Lab8_data,xlab = "Phosphate",ylab = "Yield",col = c("#00AFBB","#E7B800"))
boxplot(yield~interaction,data = Lab8_data,xlab = "NP",ylab = "Yield",col = c("#00AFBB","#E7B800"))
model <- aov(yield~fac1+fac2+fac1*fac2,data = Lab8_data)
summary(model)
library(readxl)
fact_data <- read_excel("C:/Users/Jeevan/Desktop/Christ University/Statistics/DOE/2^3_data.xlsx")
View(fact_data)
attach(fact_data)
boxplot(Yield~Factorn*Factorp*Factork,data = fact_data,xlab = "Nitrogen",
        ylab = "Yield",col = c("#00AFBB","#E7B800"))
boxplot(Yield~Factorn,data = fact_data,col = c("#00AFBB","#E7B800"),xlab = "Nitrogen",
        ylab = "Yield")
model <- aov(Yield~Factorn+Factorp+Factork+Factorn*Factorp+Factorn*Factork+Factorp*Factork+Factorn*Factorp*Factork)
summary(model)
plot(model)